apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev1
  name: test-gclient-deployment
  labels:
    app: test-gclient
    service: test-gclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gclient
  template:
    metadata:
      labels:
        app: test-gclient
    spec:
      containers:
      - name: test-gclient
        env:
        - name: ADDR
          value: test-gserver:9090
        image: albertocsm/test-gclient:latest
        ports:
        - containerPort: 9090