apiVersion: v1
kind: Service
metadata:
  name: test-gclient
  labels:
    run: test-gclient
spec:
  selector:
    app: test-gclient
  ports:
  - port: 9090
    protocol: TCP
  selector:
    run: test-gclient
  type: LoadBalancer